### ISSUE TITLE
About the error "FileNotFoundError: [Errno 2] No such file or directory"

### ISSUE THREAD

**Issue by YancyWang007** [pranavsb/RL_smart_grid#1]
There is no "B20P10" and "B101P10" in the directory.  What do the "B20P10" and "B101P10" mean?
The error is shown as follows.
Thanks for your help.
---------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "D:/Q-EOSGT/model/AnalyseDay.py", line 79, in <module>
    load_agent_dict[i] = read_model(load_agent_params[i])
  File "D:\Q-EOSGT\model\Utils.py", line 101, in read_model
    'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Q-EOSGT\\model/basic_qlearning_models/B20P10/moving_buckets/randomize_battery/dumloads999/df0.95/lr0.1/vanilla_agent_9999.pickle'
------------------------------------------------------------------------------------------------------------------------------------------

**Comment by asaelbarilan** [comment]
having the same problem. did you solve that?

**Comment by pranavsb** [comment]
Hi @YancyWang007 and @asaelbarilan

B10P10 means Battery 10 and Price 10, this is the number of discrete states for each, like `Discrete(10)` if you've used Open AI gym.

To have these pickle files, you need to first train the models, then you can run `AnalyseDay.py`
